function delhi() {
    window.alert("Delhi, officially the National Capital Territory of Delhi, is a city and a union territory of India containing New Delhi, the capital of India. It is bordered by the state of Haryana on three sides and by Uttar Pradesh to the east. The NCT covers an area of 1,484 square kilometres. According to the 2011 census, Delhi's city proper population was over 11 million, the second-highest in India after Mumbai, while the whole NCT's population was about 16.8 million. Delhi's urban area is now considered to extend beyond the NCT boundaries, and include the neighbouring satellite cities of Ghaziabad, Faridabad, Gurgaon and Noida in an area called the National Capital Region and had an estimated 2016 population of over 26 million people, making it the world's second-largest urban area according to the United Nations. Recent estimates of the metro economy of its urban area have ranked Delhi either the most or second-most productive metro area of India. Delhi is the second-wealthiest city in India after Mumbai and is home to 18 billionaires and 23,000 millionaires. Delhi ranks fifth among the Indian states and union territories in human development index. Delhi has the second-highest GDP per capita in India. Delhi is of great historical significance as an important commercial, transport, and cultural hub, as well as the political centre of India.");
}


function mumbai() {
    window.alert("Mumbai is the capital city of the Indian state of Maharashtra. According to the United Nations, as of 2018, Mumbai is the second-most populous city in the country after Delhi and the seventh-most populous city in the world with a population of roughly 20 million. As per Indian government population census of 2011, Mumbai was the most populous city in India with an estimated city proper population of 12.5 million living under Municipal Corporation of Greater Mumbai. Mumbai is the centre of the Mumbai Metropolitan Region, the sixth most populous metropolitan area in the world with a population of over 23 million. Mumbai lies on the Konkan coast on the west coast of India and has a deep natural harbour. In 2008, Mumbai was named an alpha world city. It has the highest number of millionaires and billionaires among all cities in India. Mumbai is home to three UNESCO World Heritage Sites: the Elephanta Caves, Chhatrapati Shivaji Maharaj Terminus, and the city's distinctive ensemble of Victorian and Art Deco buildings.");
}


function kolkata() {
    window.alert("Kolkata is the capital of the Indian state of West Bengal. Located on the eastern bank of the Hooghly River, the city is approximately 80 kilometres west of the border with Bangladesh.");
}

function darjeeling() {
    window.alert("Darjeeling is a city and a municipality in the Indian state of West Bengal. It is located in the Lesser Himalayas at an elevation of 2,000 metres. It is noted for its tea industry, its views of the world's third-highest mountain Kangchenjunga, and the Darjeeling Himalayan Railway, a UNESCO World Heritage Site. Darjeeling is the headquarters of the Darjeeling district which has a partially autonomous status called Gorkhaland Territorial Administration within the state of West Bengal. It is also a popular tourist destination in India.");
}

function sikkim() {
    window.alert("Sikkim is a state in northeastern India. It borders the Tibet Autonomous Region of China in the north and northeast, Bhutan in the east, Nepal in the west, and West Bengal in the south. Sikkim is also close to India's Siliguri Corridor near Bangladesh. Sikkim is the least populous and second smallest among the Indian states. A part of the Eastern Himalaya, Sikkim is notable for its biodiversity, including alpine and subtropical climates, as well as being a host to Kangchenjunga, the highest peak in India and third highest on Earth. Sikkim's capital and largest city is Gangtok. Almost 35% of the state is covered by the Khangchendzonga National Park – a UNESCO World Heritage Site.");
}

function shillong() {
    window.alert("Shillong is a hill station in the northeastern part of India and the capital of Meghalaya, which means The Abode of Clouds. It is the headquarters of the East Khasi Hills district. Shillong is the 330th most populous city in India with a population of 143,229 according to the 2011 census. It is said that the rolling hills around the town reminded the British of Scotland. Hence, they would also refer to it as the Scotland of the East. Shillong has steadily grown in size since it was made the civil station of the Khasi and Jaintia Hills in 1864 by the British. In 1874, on the formation of Assam as the Chief Commissioner's Province, it was chosen as the headquarters of the new administration because of its convenient location between the Brahmaputra and Surma valleys and more so because the climate of Shillong was much cooler than tropical India. Shillong remained the capital of undivided Assam until the creation of the new state of Meghalaya on 21 January 1972, when Shillong became the capital of Meghalaya, and Assam moved its capital to Dispur in Guwahati.");
}

function chennai() {
    window.alert("Chennai is the capital of the Indian state of Tamil Nadu. Located on the Coromandel Coast of the Bay of Bengal, it is one of the largest cultural, economic and educational centres of south India. According to the 2011 Indian census, it is the sixth-most populous city and fourth-most populous urban agglomeration in India. The city together with the adjoining regions constitutes the Chennai Metropolitan Area, which is the 36th-largest urban area by population in the world. The traditional and de facto gateway of South India, Chennai is among the most-visited Indian cities by foreign tourists. It was ranked the 43rd-most visited city in the world for the year 2015 and was ranked the 36th-most visited city in the world for the year 2019. The Quality of Living Survey rated Chennai as the safest city in India. Chennai attracts 45 percent of health tourists visiting India, and 30 to 40 percent of domestic health tourists. As such, it is termed India's health capital. Chennai has the fifth-largest urban economy of India. Chennai had the third-largest expatriate population in India, at 35,000 in 2009, 82,790 in 2011 and estimated at over 100,000 by 2016. Tourism-guide publisher Lonely Planet named Chennai as one of the top ten cities in the world to visit in 2015. Chennai is ranked as a beta-level city in the Global Cities Index, and was ranked the best city in India by India Today in the 2014 annual Indian city survey. In 2015 Chennai was named the hottest city (city worth visiting and worth living in for long term) by the BBC, citing the mixture of both modern and traditional values. National Geographic mentioned Chennai as the only South Asian city to feature in its 2015 Top 10 food cities list. Chennai was also named the ninth-best cosmopolitan city in the world by Lonely Planet. In October 2017, Chennai was added to the UNESCO Creative Cities Network (UCCN) list for its rich musical tradition. The Chennai Metropolitan Area is one of the largest municipal economies of India. More than one-third of Indias automobile industry being based in the city.");
}

function agra() {
    window.alert("Agra is a city on the banks of the Yamuna river in the Indian state of Uttar Pradesh, about 210 kilometres south of the national capital New Delhi. With a population of roughly 1.6 million, Agra is the fourth-most populous city in Uttar Pradesh and twenty-third most populous city in India.");
}

function hyderabad() {
    window.alert("Hyderabad is the capital and largest city of the Indian state of Telangana and the de jure capital of Andhra Pradesh. It occupies 650 square kilometres on the Deccan Plateau along the banks of the Musi River, in the northern part of South India. With an average altitude of 542 metres, much of Hyderabad is situated on hilly terrain around artificial lakes, including the Hussain Sagar lake, predating the city's founding, in the north of the city centre. According to the 2011 Census of India, Hyderabad is the fourth-most populous city in India with a population of 6.9 million residents within the city limits, and has a population of 9.7 million residents in the metropolitan region, making it the sixth-most populous metropolitan area in India. With an output of US$74 billion, Hyderabad has the fifth-largest urban economy in India.");
}

function bengaluru() {
    window.alert("Bangalore, officially known as Bengaluru, is the capital and the largest city of the Indian state of Karnataka. It has a population of more than 8 million and a metropolitan population of around 11 million, making it the third most populous city and fifth most populous urban agglomeration in India. Located in southern India on the Deccan Plateau, at a height of over 900 m above sea level, Bangalore is known for its pleasant climate throughout the year. Its elevation is the highest among the major cities of India.");
}

function goa() {
    window.alert("Goa is a state on the southwestern coast of India within the region known as the Konkan, and geographically separated from the Deccan highlands by the Western Ghats. It is surrounded by the Indian states of Maharashtra to the north and Karnataka to the east and south, with the Arabian Sea forming its western coast. It is India's smallest state by area and its fourth-smallest by population. Goa has the highest GDP per capita among all Indian states, two and a half times as high as the GDP per capita of the country as a whole. The Eleventh Finance Commission of India named Goa the best-placed state because of its infrastructure, and India’s National Commission on Population rated it as having the best quality of life in India. It is the third-highest ranking among Indian states in human development index.");
}

function andamans() {
    window.alert("Andaman and Nicobar Islands is a union territory of India consisting of 572 islands, of which 38 are inhabited, at the junction of the Bay of Bengal and the Andaman Sea.");
}
